[package]
name = "editor-types-parser"
version = "0.0.1"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nom = { workspace = true }
thiserror = "1.0.57"
